name: pandaprompt
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  uuid: ^3.0.6
  overlay_support: ^1.2.1
  flutter_local_notifications: ^13.0.0
  lottie: ^2.2.0
  flutter_secure_storage: ^8.0.0
  flutter_launcher_icons: ^0.13.1
  launcher_name: ^1.0.2
  flutter_native_splash: 

launcher_name:
  default: "PandaPrompt"
  es: "PandaPrompt"
  fr: "PandaPrompt"
  de: "PandaPrompt"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image.jpg
    - assets/images/image.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/logo.png

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter_native_splash:
  image: "assets/images/image.png"
  color: "42a5f5"
